### PR TITLE
1.18.x nameable tiles

### LINKED ISSUE #6371: Personal chest naming does not save when placed and picked-up
#### Issue description:
When a personal chest is named from an anvil and placed, once it is picked up, the item loses its custom name. This problem does not occur when using normal Minecraft chests, for reference.

#### Steps to reproduce:
1. Name a personal chest using an anvil.
2. Place the personal chest.
3. Pick up the personal chest.
4. The name should be reverted to "Personal chest".

#### Version: 1.16.1
**Forge: 1.16.1-forge-32.0.69** 
**Mekanism: Mekanism-1.16.1-10.0.2.425**

### PR DESCRIPTION
**Pull request by Matyrobbrt**
## Changes proposed in this pull request:
1.18 version of #7379
Fixes #6371

### CODE REVIEW

File: src/main/java/mekanism/common/tile/base/TileEntityMekanism.java [hunk 1]
```diff
@@ -738,6 +783,10 @@ public CompoundTag getReducedUpdateTag() {
             component.addToUpdateTag(updateTag);
         }
         updateTag.putFloat(NBTConstants.RADIATION, radiationScale);
+        // Sync the name with clients
+        if (this.customName != null && isNameable()) {
+            updateTag.putString(NBTConstants.CUSTOM_NAME, Component.Serializer.toJson(this.customName));
+        }
```
Comment (pupnewfster) [inline src/main/java/mekanism/common/tile/base/TileEntityMekanism.java:789]: What is the use of syncing this stuff in the update tag? (Especially after the changes I made yesterday). Is it just so if a mod calls the methods on the client they have results, given I am honestly not quite sure how much that matters.

File: src/main/java/mekanism/common/tile/base/TileEntityMekanism.java [hunk 2]
```diff
@@ -431,8 +438,38 @@ public void addComponent(ITileComponent component) {
...
     public Component getName() {
-        return TextComponentUtil.translate(Util.makeDescriptionId("container", getBlockType().getRegistryName()));
+        return hasCustomName() ? getCustomName() : TextComponentUtil.build(getBlockType());
+    }
+
+    @Nonnull
+    @Override
+    @SuppressWarnings("ConstantConditions")
+    public Component getDisplayName() {
+        return hasCustomName() ? getCustomName() : TextComponentUtil.translate(Util.makeDescriptionId("container", getBlockType().getRegistryName()));
```
Comment (pupnewfster) [inline src/main/java/mekanism/common/tile/base/TileEntityMekanism.java:451]: I added this as a different implementation than getName just for more "accurate" results at least for purposes as we use display name for the container, but I am wondering if this should maybe instead be:
```java
if (isNameable()) {
//current return
}
return TextComponentUtil.build(getBlockType());
```
Thoughts? Alternatively maybe move the logic of this return to AttributeGUI and remove the getDisplayName override allowing it to be the default in case mods make assumptions and want the actual name not the name for displaying in containers.

File: src/main/java/mekanism/common/tile/TileEntityBoundingBlock.java [hunk 3]
```diff
@@ -27,7 +30,7 @@
 /**
  * Multi-block used by wind turbines, solar panels, and other machines
  */
-public class TileEntityBoundingBlock extends TileEntityUpdateable implements IUpgradeTile, ISecurityTile {
+public class TileEntityBoundingBlock extends TileEntityUpdateable implements IUpgradeTile, ISecurityTile, Nameable {
```
Comment (pupnewfster) [inline src/main/java/mekanism/common/tile/TileEntityBoundingBlock.java:33]: Is there really much use in making the bounding blocks be Nameable, or is this just in case other mods might want to query information via them? I suspect at least for Jade and TOP this may not be needed due to redirects I already do, but if you think it is worth leaving them in we can.

File: src/main/java/mekanism/common/tile/base/TileEntityMekanism.java (hunk 2 above)
Comment (Matyrobbrt) [reply src/main/java/mekanism/common/tile/base/TileEntityMekanism.java:451]: I think that we should wrap that return inside the `isNameable`, because if it isn't showing the custom name is useless.

File: src/main/java/mekanism/common/tile/base/TileEntityMekanism.java (hunk 1 above)
Comment (Matyrobbrt) [reply src/main/java/mekanism/common/tile/base/TileEntityMekanism.java:789]: I'm not sure if the syncing is needed anymore. Let me see 🤔

File: src/main/java/mekanism/common/tile/TileEntityBoundingBlock.java (hunk 3 above)
Comment (Matyrobbrt) [reply src/main/java/mekanism/common/tile/TileEntityBoundingBlock.java:33]: From my testing, Jade needed that in order to pickup the custom name, if it exists. I'd leave it there in case any other mod needs the block's name for whatever reason.

File: src/main/java/mekanism/common/tile/base/TileEntityMekanism.java [hunk 4]
```diff
@@ -431,8 +438,46 @@ public void addComponent(ITileComponent component) {
...
     @Nonnull
+    @Override
+    @SuppressWarnings("ConstantConditions")
     public Component getName() {
-        return TextComponentUtil.translate(Util.makeDescriptionId("container", getBlockType().getRegistryName()));
+        final var defaultName = TextComponentUtil.build(getBlockType());
+        if (isNameable()) {
+            return hasCustomName() ? getCustomName() : defaultName;
+        }
+        return defaultName;
```
Comment (pupnewfster) [inline src/main/java/mekanism/common/tile/base/TileEntityMekanism.java:448]: Given getCustomName returns null if it isn't nameable, this can stay as it was before `return hasCustomName() ? getCustomName() : TextComponentUtil.build(getBlockType());`

File: src/main/java/mekanism/common/tile/base/TileEntityMekanism.java [hunk 5]
```diff
@@ -431,8 +438,46 @@ public void addComponent(ITileComponent component) {
...
+    }
+
+    @Nonnull
+    @Override
+    @SuppressWarnings("ConstantConditions")
+    public Component getDisplayName() {
+        final var defaultName = TextComponentUtil.translate(Util.makeDescriptionId("container", getBlockType().getRegistryName()));
```
Comment (pupnewfster) [inline src/main/java/mekanism/common/tile/base/TileEntityMekanism.java:455]: Two things:
1. For now I think I am going to hold off in a big way from using var in Mekanism
2. The reason I was mentioning wrapping in isNameable, is not all tiles have this translation key now. Which is why I was saying to use a different fallback `TextComponentUtil.build(getBlockType())` for if it is not nameable, but use this one for if it is nameable and just doesn't have a custom name.
